### ISSUE TITLE
NSW Property data from last 20 years (starting from 2000)

### ISSUE THREAD

**Issue by rajeshkendhuli** [jameselks/nsw-property-sales-data-cleaner#1]
Please provide the NSW property data from last 20 years starting from 2000

**Comment by jameselks** [comment]
Hey @rajeshkendhuli Sorry I missed your comment. You can go back as far as 1990. In `1-download.py` you just need to change `years_to_collect` from 6 (which right now would be 2017 to 2023) to 23 (which right now would be 2000 to 2023).
