### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by mdav43** [jameselks/nsw-property-sales-data-cleaner#2]
this is pretty awesome. really appreciate the sharing of the code - saved me a lot of time. 

I'm going to try and geocode and then overlay on a Kepler.gl map for some extra visualizations.

**Comment by jameselks** [comment]
Thanks @mdav43 I'm glad it was helpful.
Keep me posted on how you go (it's a lot to geocode 😬) - would love to see what you do with it.

**Comment by mdav43** [comment]
attached is a sample of potential output. I used the gnat address data to do a lookup (not very clean yet as lookups a bit messy) but free compared to a google maps geocode. 

https://github.com/jameselks/nsw-property-sales-data-cleaner/assets/3327386/d03a168f-743b-4fd5-8078-0dbcbfa7e554

once I have it clean I'l share a link so you can add if you want to.

**Comment by Maxim-Mazurok** [comment]
Oh, wow, what are the odds, I've also decided to spend my Saturday playing with the data :D
Thanks for compiling it! Will share my findings in a separate ticket.

**Comment by jameselks** [comment]
Oh this is cool, please share!
