### ISSUE TITLE
My findings

### ISSUE THREAD

**Issue by Maxim-Mazurok** [jameselks/nsw-property-sales-data-cleaner#3]
First of all, thanks for compiling this, really helped!

---

So I've used the data from the website (`nsw-property-sales-data-updated20240302.csv`) to estimate distribution of CAGR for individual residential properties.
Basically, I wanted to answer the question: if I buy a property, what are the chances of being a loser on the wrong end of the statistics :)

From my sources, average CARG in Sydney is about 6-7%-ish, depending on the period.

And my analytics of this data for all NSW seems to confirm that. Also it seems to suggest that it's more likely to be a "winner". And if you "lose" - then not by that much.

There are some outliers, like 100% lost or 100%+ gained. While this normally would be true (house burned down, ocean ate your land, etc.) in those cases that I've inspected - it just seems to be bad data (in the source).

For example, I see someone buy a house for 6mil, then sell it for 200k as land. My friend realtor told me that most likely it was split or something, but that wan't reflected in data, no lot no, no unit, nothing like that, just the same address.

In another case I saw someone buy land for 29mil, 2 months later sold for 35mil. Obviously, this is a re-seller and isn't typical.

So, the data could be cleaner. But anyway, here are my charts:

![image](https://github.com/jameselks/nsw-property-sales-data-cleaner/assets/7756211/f4e844b7-ad01-4c61-92e5-8ce2a944712f)

I hope this helps someone!

**Comment by jameselks** [comment]
Oh this is an interesting analysis I hadn't thought of, thank you @Maxim-Mazurok! I will add to the Notebook when I get a chance.
