### ISSUE TITLE
Earlier years column mappings for .DAT files

### ISSUE THREAD

**Issue by Phill-Moore** [jameselks/nsw-property-sales-data-cleaner#4]
Hi James
Great effort in going to the effort of making this data available and really appreciate you providing these cleanup python scripts. So I've downloaded 30+ years of historical sales data and have written some additional python scripts to further clean data and remove some duplicate entries.

Given you have a excellent background with Column data, could you elaborate some of the meanings of the data types in the columns (I can extrapolate some from the cleaned data, but some is still unclear in the RAW data.
EG in earlier years there are some columns missing in comparison to later years >2000 I believe. 

Examples with Unknown Headers
B ??,  81/82??,  (ARCHIVE/VALNET1)??, I Assume Property ID?, PROPERTY UNIT NUMBER,  PROPERTY STREET NUMBER, SUBURB/LOCATION, POSTCODE, PURCHASE DATE, PROPERTY SALE PRICE, LOT/SP and Other things to parse?? 
   
B,81,VALNET1,875430000000.00, 602975, , 49, MERELYNNE AV, PENNANT HILLS, 2120,  25/2/1999, 1046000, LOT 29 DP 736172.
B, 82, ARCHIVE, 1820100000000.00, 657236, , 18, MORRISON PL,  PENNANT HILLS,  2120, 16/12/1999, 410000, LOT 14 DP 237483 DIM PT ARC26.14/28.04X27.41/39.17

Could you provide some guidance for these values?
Regards
Phill Moore
https://www.linkedin.com/in/phillmoore/

**Comment by jameselks** [comment]
Hi Phil

Sorry for the slow response. Did you get to the bottom of this?

The data format changes in 2001. You can see the file format documentation here:
https://valuation.property.nsw.gov.au/embed/propertySalesInformation

So are you saying the data pre-2001 is wrong in the exported csv? I am happy to look at integrating pre-2001 data into the transform process, but I will need a few weeks as life is busy at the moment! Otherwise would be happy for a PR if you have solved it ;)

James.

**Comment by jameselks** [comment]
I added the Valuer General documentation to the repo
https://github.com/jameselks/nsw-property-sales-data-cleaner/commit/fbb02d7eb24aae860374f2343d847b6a9cbf1bbb

**Comment by Phill-Moore** [comment]
Hi JamesThanks for responding.Yep, have now massively cleaned data.Check out plotspot.com.au and have a play.RegardsPhillOn 8 Aug 2024, at 7:29 PM, James Elks ***@***.***> wrote:﻿
Closed #4 as completed.

**Comment by jameselks** [comment]
Hey @Phill-Moore just wanted to come back to you and say all 35 years of data is now available. Enjoy.
